name: build

on: [push, pull_request]

env:
  GOPATH: /tmp/go
  # Because some tests require explicit setting of GOPATH. TODO: FIX THEM.
   
jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    
    if: "!contains(github.event.head_commit.message, 'SKIP CI')"
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: ['stable']

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
         go-version: '1.14'

      - name: Install dependencies
        run: npm install
      
      - name: Compile
        run: npm run vscode:prepublish

      - name: Test Secret
        run: |
          echo "Test Secret: ${TEST_TOKEN}" | awk '{print tolower($0)}'
          echo "Github Token: ${GITHUB_TOKEN//[0-9a-f]/X}"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'SKIP CI')"

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: 'npm install --frozen-lockfile'
        shell: bash

      - name: Lint check
        run: npm run lint
